### ISSUE TITLE
Error when compile VS2019

### ISSUE THREAD

**Issue by learningit25** [MaksimAdamenko/Youtube-Subscribers#1]
When I compile, it appears error 

System.NullReferenceException
  HResult=0x80004003
  Message=Stand
  Source=Youtube-Subscribers
  StackTrace:
   at Youtube_Subscribers.Config..cctor() in\Youtube-Subscribers\App\Config.cs:line 19

Stand = Environment.GetEnvironmentVariable("stand") 
Please help me how can i compile it

Thank you

**Comment by MaksimAdamenko** [comment]
I have not yet completed the README.md. For the application to work, a working Postgresql database is required in which statistics on channels will be saved.
You also need to set up environment variables as in this example https://www.ryadel.com/en/net-core-3-understanding-environment-variables/.
"botFatherToken": "****", - Telegram bot token for receiving logs
"TimeScanRestart": "****", - channel scanning frequency
"botToken": "****", - the bot token that will receive messages
"MyYoutubeApiKey": "****", - your Youtube Api key
"stand": "devWindows", - here you can specify the name of the launch environment
"MyIdTelegram": "210115760", - your Id in telegram
"PostgresConnectString": - connection string to postgresql

**Comment by MaksimAdamenko** [comment]
I have not yet completed the README.md. For the application to work, a working Postgresql database is required in which statistics on channels will be saved.
You also need to set up environment variables as in this example https://www.ryadel.com/en/net-core-3-understanding-environment-variables/.
"botFatherToken": "****", - Telegram bot token for receiving logs
"TimeScanRestart": "****", - channel scanning frequency
"botToken": "****", - the bot token that will receive messages
"MyYoutubeApiKey": "****", - your Youtube Api key
"stand": "devWindows", - here you can specify the name of the launch environment
"MyIdTelegram": "****", - your Id in telegram
"PostgresConnectString": - connection string to postgresql

**Comment by learningit25** [comment]
Thank you very much. I will try it.
I don't understand what is different botFatherToken & botToken because I only know botToken.
Can you help me with how to get botFatherToken ?

**Comment by MaksimAdamenko** [comment]
> Thank you very much. I will try it.
> I don't understand what is different botFatherToken & botToken because I only know botToken.
> Can you help me with how to get botFatherToken ?

botFatherToken - is any bot (you can even use botToken) to get statistics of the application when it is running, for example on AWS

stand - is just a label for understanding which machine the application is running on (can be any text)

**Comment by learningit25** [comment]
Thank you @MaksimAdamenko 
I will try it.
